import 'dart:ui';

abstract class LightThemeColors {
  static const Color seed = Color(0xFFAE2D3D);
  static const Color mdThemeLightPrimary = Color(0xB5808BCA);
  static const Color mdThemeLightOnPrimary = Color(0xFFFFFFFF);
  static const Color mdThemeLightPrimaryContainer = Color(0xFFFFDADA);
  static const Color mdThemeLightOnPrimaryContainer = Color(0xFF40000B);
  static const Color mdThemeLightErrorContainerMdThemeLightSecondary = Color(0xFF9C4049);
  static const Color mdThemeLightOnSecondary = Color(0xFFFFFFFF);
  static const Color mdThemeLightSecondaryContainer = Color(0x4D4C62E7);
  static const Color mdThemeLightSecondaryTwoContainer = Color(0x4D6676D2);
  static const Color mdThemeLightSecondaryThirdContainer = Color(0xFF0C3EA9);
  static const Color mdThemeLightOnSecondaryContainer = Color(0xFF40000C);
  static const Color mdThemeLightTertiary = Color(0xFF9C4049);
  static const Color mdThemeLightOnTertiary = Color(0xFFFFFFFF);
  static const Color mdThemeLightTertiaryContainer = Color(0xFFFFDADA);
  static const Color mdThemeLightOnTertiaryContainer = Color(0xFF40000C);
  static const Color mdThemeLightError = Color(0xFFBA1A1A);
  static const Color mdThemeLightErrorContainer = Color(0xFFFFDAD6);
  static const Color mdThemeLightOnError = Color(0xFFFFFFFF);
  static const Color mdThemeLightOnErrorContainer = Color(0xFF410002);
  static const Color mdThemeLightBackground = Color(0xFFFFFFFF);
  static const Color mdThemeLightOnBackground = Color(0xFF201A1A);
  static const Color mdThemeLightSurface = Color(0xFFFFFFFF);
  static const Color mdThemeLightOnSurface = Color(0xFF201A1A);
  static const Color mdThemeLightSurfaceVariant = Color(0xFFF4DDDD);
  static const Color mdThemeLightOnSurfaceVariant = Color(0xFF524343);
  static const Color mdThemeLightOnSurfaceSecondVariant = Color(0xFF525252);
  static const Color lightBlue = Color(0x7BDDDFF6);
  static const Color mdThemeLightOutline = Color(0xFF857373);
  static const Color mdThemeLightInverseOnSurface = Color(0xFFFBEEED);
  static const Color mdThemeLightInverseSurface = Color(0xFF362F2F);
  static const Color mdThemeLightInversePrimary = Color(0xFFFFB3B4);
  static const Color mdThemeLightShadow = Color(0xFF000000);
  static const Color mdThemeLightSurfaceTint = Color(0xFFAE2D3D);
  static const Color positiveCheck = Color(0xB5808BCA);
  static const Color positiveCheckBack = Color(0xB5CFD7FC);
  static const Color sendMessageColor = Color(0xB5C1CBF6);
  static const Color negativeCheck = Color(0xFFA3A4A9);
  static const Color negativeCheckBack = Color(0xFFF1F1F1);
  static const Color blueTextColor = Color(0xFF3E5481);
  static const Color mdThemeLightSurfaceTintColor = Color(0xFFAE2D3D);
}